LunchBoxS/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('home.urls')),
    path('', RedirectView.as_view(url='/home/', permanent=True)),
    path('', include('django_prometheus.urls')),
]

from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns() + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

home/urls.py
from . import views
from django.conf.urls import url

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^administrator/$', views.administrator, name='administrator'),
    url(r'^employee/$', views.employee, name='employee'),
    url(r'^LogoutProfile/$', views.LogoutProfile, name='logoutProfile'),
    url(r'^LunchBox/(?P<lunch_id>[0-9]+)/$', views.LunchRedaction, name='lunchRedaction'),
    url(r'^LunchBox/Create/$', views.LunchCreate, name='lunchCreate'),
    url(r'^Empl/Create/$', views.EmplCreate, name='emplCreate'),
    url(r'^Empl/(?P<empl_id>[0-9]+)/Type/Create/$', views.TypeCreate, name='typeCreate'),
    url(r'^Order/(?P<order_id>[0-9]+)/$', views.OrderV, name='order'),
    url(r'^employee-orders/', views.employee_orders, name='prepare'),
    url(r'^statistics/', views.statistics, name='statistics'),
    url(r'^ajax/employee/', views.statistics_employee, name='statistics_employee'),
    url(r'^ajax/employee_graf/', views.statistics_employee_graf, name='employee_graf'),
    url(r'^ajax/sales/', views.statistics_sales, name='statistics_sales'),
    url(r'^ajax/sales_content/', views.sales_content, name='sales_content'),
    url(r'^ajax/sales_content_day/', views.sales_content_day, name='sales_content_day'),
    url(r'^ajax/sales_month/graf/', views.sales_graf_month, name='sales_graf_month'),
    url(r'^ajax/sales_day/graf/', views.sales_graf_day, name='sales_graf_day'),
    url(r'^ajax/lunchboxs/', views.statistics_lunchboxs, name='statistics_lunchboxs'),
    url(r'^ajax/lunchboxs_graf/', views.lunchbox_graf, name='lunchbox_graf'),
]

home/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


# тип пользователя, определяющий уровень доступности
# 0 - клиент
# 1 - сотрудник
# 2 - администратор
class Type(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    level = models.IntegerField(default=0)

    @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            Type.objects.create(user=instance)


class LunchBox(models.Model):
    title = models.CharField(max_length=255, unique=True)
    img = models.ImageField(upload_to="images/")
    description = models.CharField(max_length=1000)
    price = models.IntegerField()
    addition = models.CharField(max_length=50)


# Количество ланчбоксов, 0 по умолчанию
class NumberOfLunchBox(models.Model):
    lunchbox = models.OneToOneField(LunchBox, on_delete=models.CASCADE)
    number = models.IntegerField(default=0)

    @receiver(post_save, sender=LunchBox)
    def create_lunch_box(sender, instance, created, **kwargs):
        if created:
            NumberOfLunchBox.objects.create(lunchbox=instance)


class Basket(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    lunchbox = models.OneToOneField(LunchBox, on_delete=models.CASCADE)
    number = models.IntegerField(default=0)
    price = models.IntegerField(default=0)


class Order(models.Model):
    id = models.AutoField(primary_key = True)
    client = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    price = models.IntegerField(default=0)


class OrderComposition(models.Model):
    order = models.ForeignKey(Order, related_name='order_compositions', on_delete=models.CASCADE)
    lunchbox = models.ForeignKey(LunchBox, related_name='lunchbox_info', on_delete=models.CASCADE)
    number = models.IntegerField()


class PastOrder(models.Model):
    id = models.AutoField(primary_key = True)
    client = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateTimeField()
    price = models.IntegerField(default=0)
    employee = models.CharField(max_length=50, default="")


class PastOrderComposition(models.Model):
    order = models.ForeignKey(PastOrder, related_name='pastorder_compositions', on_delete=models.CASCADE)
    lunchbox = models.ForeignKey(LunchBox, related_name='pastlunchbox_info', on_delete=models.CASCADE)
    number = models.IntegerField()


class Status(models.Model):
    name = models.CharField(max_length=30)
    st = models.BooleanField(default=False)

home/views.py
import datetime

from django.shortcuts import render, get_object_or_404, redirect
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from .models import Type, LunchBox, User, Order, NumberOfLunchBox, OrderComposition, PastOrder, PastOrderComposition, \
    Status
from .form import LunchBoxForm, DelLunchBoxForm, DelUserForm, SignUpForm, ReadyOrderForm, SearchOrderForm, StatusBusy
from .form import TypeUserForm, NumberOfLunchBoxForm, TypeForm


def index(request):
    if request.method == 'POST':
        user = authenticate(
            username=request.POST.get('username'),
            password=request.POST.get('password1'),
        )
        if user is not None:
            if user.is_active:
                login(request, user)
                lev = Type.objects.get(user=user)
                if (lev.level == 1):
                    return redirect('employee')
                if (lev.level == 2):
                    return redirect('administrator')
            else:
                print("The password is valid, but the account has been disabled!")
        else:
            print("The username and password were incorrect.")

    return render(request, 'index.html')


def LogoutProfile(request):
    logout(request)

    return redirect('index')


def administrator(request):
    userP = get_object_or_404(User, username=request.user.username)
    users = User.objects.filter(type__level__gt=0).exclude(username=request.user.username)
    lbs = LunchBox.objects.all()
    deleteLb = DelLunchBoxForm()
    deleteEmpl = DelUserForm()
    redaction_number = NumberOfLunchBoxForm()
    if request.method == 'POST':
        redaction_number = NumberOfLunchBoxForm(request.POST)
        deleteLb = DelLunchBoxForm(request.POST)
        deleteEmpl = DelUserForm(request.POST)

        if deleteEmpl.is_valid():
            del_id = deleteEmpl.cleaned_data['id_user']
            User.objects.filter(id=del_id).delete()
            return redirect('administrator')
        else:
            deleteEmpl = DelUserForm()

        if deleteLb.is_valid():
            del_id = deleteLb.cleaned_data['del_lunchbox']
            LunchBox.objects.filter(id=del_id).delete()
            return redirect('administrator')
        else:
            deleteLb = DelLunchBoxForm()

        if redaction_number.is_valid():
            lunchbox = LunchBox.objects.get(id=redaction_number.cleaned_data['id_lunchbox'])
            num = redaction_number.cleaned_data['number']
            lunchbox_num = NumberOfLunchBox()
            try:
                lunchbox_num = NumberOfLunchBox.objects.get(lunchbox=lunchbox)
            except ObjectDoesNotExist:
                lunchbox_num = None

            if lunchbox_num != None:
                lunchbox_num = NumberOfLunchBox.objects.get(lunchbox=lunchbox)
                lunchbox_num.number = num
                lunchbox_num.save()
                return redirect('administrator')
            else:
                new_lb_num = NumberOfLunchBox.objects.create(lunchbox=lunchbox, number=num)
                new_lb_num.save()
        else:
            form = LunchBoxForm()

    return render(request, 'admin.html', {'lbs': lbs, 'users': users, 'userP': userP})


def EmplCreate(request):
    user_add = SignUpForm()
    if request.method == 'POST':
        user_add = SignUpForm(request.POST)
        if user_add.is_valid():
            z = user_add.save(commit=False)
            z.save()
            return HttpResponseRedirect(reverse('typeCreate', args=(z.id,)))
        else:
            user_add = SignUpForm()

    return render(request, 'create_eml.html')


def TypeCreate(request, empl_id):
    empl = get_object_or_404(User, id=empl_id)
    create_type = TypeForm()
    if request.method == 'POST':
        create_type = TypeForm(request.POST)
        if create_type.is_valid():
            t = Type.objects.get(user=empl)
            t.level = create_type.cleaned_data['level']
            t.save()
            return redirect('administrator')
        else:
            form = TypeForm()

    return render(request, 'create_type.html')


def employee(request):
    status = get_object_or_404(Status, name="busy")
    st = 0
    if status.st == False:
        st = 0
    else:
        st = 1
    userP = get_object_or_404(User, username=request.user.username)
    orders = Order.objects.all()
    readyOrder = ReadyOrderForm()
    searchOrder = SearchOrderForm()
    stform = StatusBusy()
    if request.method == 'POST':
        readyOrder = ReadyOrderForm(request.POST)
        searchOrder = SearchOrderForm(request.POST)
        stform = StatusBusy(request.POST)
        if stform.is_valid():
            s = stform.cleaned_data['id_status']
            p = False
            if s == 0:
                p = False
            else:
                p = True
            status.st = p
            status.save()
            return redirect('employee')
        else:
            stform = StatusBusy()
        if readyOrder.is_valid():
            id = readyOrder.cleaned_data['id_ready']
            return HttpResponseRedirect(reverse('order', args=(id,)))
        else:
            readyOrder = ReadyOrderForm()
        if searchOrder.is_valid():
            id = searchOrder.cleaned_data['id_search']
            try:
                o = Order.objects.get(id=id)
            except ObjectDoesNotExist:
                o = None

            if o == None:
                return redirect('employee')
            return HttpResponseRedirect(reverse('order', args=(id,)))
        else:
            searchOrder = ReadyOrderForm()
    return render(request, 'employee.html', {'userP': userP, 'orders': orders, 'st': st})


def employee_orders(request):
    if request.method == 'GET':
        orders = Order.objects.all()
        return render(request, 'prepare.html', {'orders': orders})


def LunchRedaction(request, lunch_id):
    lb = get_object_or_404(LunchBox, id=lunch_id)
    redaction_lb = LunchBoxForm()
    if request.method == 'POST':
        redaction_lb = LunchBoxForm(request.POST, request.FILES)
        if redaction_lb.is_valid():
            lb.title = redaction_lb.cleaned_data['title']
            lb.img = redaction_lb.cleaned_data['img']
            lb.description = redaction_lb.cleaned_data['description']
            lb.price = redaction_lb.cleaned_data['price']
            lb.addition = redaction_lb.cleaned_data['addition']
            lb.save()
            return redirect('administrator')
        else:
            form = LunchBoxForm()

    return render(request, 'redaction_lunch.html', {'lb': lb})


def LunchCreate(request):
    create_lb = LunchBoxForm()
    if request.method == 'POST':
        create_lb = LunchBoxForm(request.POST, request.FILES)
        if create_lb.is_valid():
            p = create_lb.save(commit=False)
            p.save()
            return redirect('administrator')
        else:
            form = LunchBoxForm()

    return render(request, 'create_lunch.html')


def OrderV(request, order_id):
    order = Order.objects.get(id=order_id)
    username = request.user.username
    readyOrder = ReadyOrderForm()
    if request.method == 'POST':
        readyOrder = ReadyOrderForm(request.POST)
        if readyOrder.is_valid():
            order = Order.objects.get(id=readyOrder.cleaned_data['id_ready'])
            ordercomposition = OrderComposition.objects.filter(order=order)
            z = PastOrder.objects.create(client=order.client, date=order.date, price=order.price,
                                         employee=username)
            z.save()
            for i in ordercomposition:
                p = PastOrderComposition.objects.create(order=z, lunchbox=i.lunchbox, number=i.number)
                p.save()

            order.delete()
            return redirect('employee')
        else:
            readyOrder = ReadyOrderForm()
    return render(request, 'order.html', {'order': order,'username': username})


def statistics(request):
    userP = get_object_or_404(User, username=request.user.username)

    return render(request, 'statistics.html', {'userP': userP})


def list_employee_add(name, list):
    for i in list:
        if i[0] == name:
            p = i[1] + 1
            i[1] = p
    return list


def statistics_employee(request):
    employee = User.objects.filter(type__level=1)
    order = PastOrder.objects.all()
    list_employee = list()
    for i in employee:
        list_employee.append([i.username, 0])
    for i in order:
        list_employee_add(i.employee, list_employee)
    return render(request, 'statistics_employee.html', {'list_employee': list_employee})

def statistics_employee_graf(request):
    if request.method == 'GET':
        employee_name = request.GET.get('employee_name')
        day_start = request.GET.get('day_start')
        day_end = request.GET.get('day_end')
        month_start = request.GET.get('month_start')
        month_end = request.GET.get('month_end')
        year_start = request.GET.get('year_start')
        year_end = request.GET.get('year_end')
        start_date = datetime.date(int(year_start), int(month_start), int(day_start))
        end_date = datetime.date(int(year_end), int(month_end), int(day_end))
        order_period = PastOrder.objects.filter(date__range=(start_date, end_date), employee=employee_name).order_by("date")
        list_order = list()
        for i in order_period:
            d = i.date.day
            y = i.date.year
            m = i.date.month
            if (proverka_y_m_d(d, y, m, list_order) == True):
                list_order = add_y_m_d(d, y, m, list_order, i.price)
            else:
                list_order.append([y, m, d, 1, i.price])
        return render(request, 'employee/graf.html', {'list_order': list_order})


def statistics_sales(request):
    return render(request, 'statistics_sales.html')

home/templates/admin.html
{% extends "base_index.html" %}

{% block title %}<title>LanchBox</title>{% endblock %}
{% block style%}
    {% load static %}
    <link href="{% static 'css/style_ad.css' %}" rel="stylesheet" >
{% endblock %}
{% block body %}
    <header>
		<div class="logotip">
			<h1>LunchBox</h1>
		</div>

		<div class="employee">
			<p>Администратор:</p>
			<p>{{userP.username}}</p>
			<a class="stat" href="{% url 'statistics'%}"><button>СТАТИСТИКА</button></a>
            <a href="{% url 'logoutProfile'%}"><button>ВЫЙТИ</button></a>
		</div>
	</header>
	<main>
		<div class="boxs">
			{% for lb in lbs %}
			<div class="lbox">
				<h3>{{lb.title}}</h3>
				<img src="{{MEDIA_URL}}{{ lb.img.url}}">
				<p>Описание:</p>
				<p>{{lb.description}}</p>
				<p>Цена:</p>
				<p class="price">{{lb.price}} руб.</p>

				<form class="formkol" action="." method="post">
					{% csrf_token %}
					<p>Количество:</p>
					<input type="hidden" name="id_lunchbox" id="id_id_lunchbox" value="{{lb.id}}">
					<p><input type="number" style="text-align:center;" name="number" id="id_number" value="{{lb.numberoflunchbox.number}}" required></p>
					<button type="submit" class="kol">ИЗМЕНИТЬ КОЛИЧЕСТВО</button>
				</form>

<a href="{% url 'lunchRedaction' lb.id %}"><button class="redaction">РЕДАКТИРОВАТЬ</button></a>

				<form action="." method="post">
					{% csrf_token %}
					<input type="hidden" name="del_lunchbox" id="id_del_lunchbox" value="{{lb.id}}">
					<button class="del" type="submit">УДАЛИТЬ</button>
				</form>

			</div>
    		{% endfor %}
			<div class="lbox">
				<a href="{% url 'lunchCreate' %}"><button type="submit" class="add">ДОБАВИТЬ</button></a>
			</div>
		</div>
		<div class="empls">
			{% for user in users %}
			<div class="empl">
				{% if user.type.level == 1 %}
				<h3>Сотрудник</h3>
				{% else %}
				<h3>Администратор</h3>
				{% endif %}
				<p class="eInfo">{{user.username}}</p>
				<form action="." method="post">
					{% csrf_token %}
					<input type="hidden" name="id_user" id="id_id_user" value="{{user.id}}">
					<button class="del" type="submit">УДАЛИТЬ</button>
				</form>
			</div>
    		{% endfor %}
			<div class="empl">
				<a href="{% url 'emplCreate' %}"><button type="submit" class="add">ДОБАВИТЬ</button></a>
			</div>
		</div>
	</main>
{% endblock %}

home/templates/base_index.html
<!DOCTYPE html>
<html lang="ru">
<head>
	<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	{% block title %}{% endblock %}
    {% block style %}{% endblock %}
</head>
<body>
	{% block body %}

	{% endblock %}
</body>
</html>

home/templates/create_eml.html
{% block title %}<title>LanchBox</title>{% endblock %}
{% block style%}
    {% load static %}
    <link href="{% static 'css/style_lunch.css' %}" rel="stylesheet" >
{% endblock %}
{% block body %}
    <div class="entry">
        {% load static %}
		<h1>Добавление сотрудника</h1>
		<form method="post" action=".">
			{% csrf_token %}
		    <table>
		        <tr>

		            <td><p>Имя пользователя:</p><input type="text" name="username" maxlength="150" autofocus required id="id_username"></td>
		        </tr>
		        <tr>

		            <td><p>Пароль:</p><input type="password" name="password1" required id="id_password1"></td>
		        </tr>
		        <tr>

		            <td><p>Подтвердите пароль:</p><input type="password" name="password2" required id="id_password2"></td>
		        </tr>
		        <tr>
		            <td><input type="submit" value="ДОБАВИТЬ"></td>
		        </tr>
		    </table>
		</form>
	</div>
{% endblock %}

home/templates/create_lunch.html
{% block title %}<title>LanchBox</title>{% endblock %}
{% block style%}
    {% load static %}
    <link href="{% static 'css/style_lunch.css' %}" rel="stylesheet" >
{% endblock %}
{% block body %}
    <div class="entry">
        {% load static %}
		<h1>Добавление ланчбокса</h1>
		<form method="post" action="." enctype="multipart/form-data">
			{% csrf_token %}
		    <table>
		        <tr>
		            <td><p>НАЗВАНИЕ</p><input type="text" name="title" autofocus id="id_title" required></td>
		        </tr>
		        <tr>
		            <td><p>ФОТО</p><input type="file" name="img" accept="image/*" required id="id_img"></td>
		        </tr>
				<tr>
					<td><p>ОПИСАНИЕ</p><textarea rows="3" type="text" name="description" autofocus id="id_description" required></textarea></td>
		        </tr>
		        <tr>
		            <td><p>ЦЕНА</p><input type="number" name="price" id="id_price" required></td>
		        </tr>
				<tr>
		            <td><p>ТИП</p><input type="text" name="addition" autofocus id="id_addition"></td>
		        </tr>
		        <tr>
		            <td><input type="submit" value="ДОБАВИТЬ"></td>
		        </tr>
		    </table>
		</form>
	</div>
{% endblock %}

home/templates/create_type.html
{% block title %}<title>LanchBox</title>{% endblock %}
{% block style%}
    {% load static %}
    <link href="{% static 'css/style_lunch.css' %}" rel="stylesheet" >
{% endblock %}
{% block body %}
    <div class="entry">
        {% load static %}
		<h1>Уровень</h1>
		<form method="post" action=".">
			{% csrf_token %}
		    <table>
		        <tr>
		            <td>
						<button class="level" type="submit" name="level" value="1">СОТРУДНИК</button>
						<button class="level" type="submit" name="level" value="2">АДМИНИСТРАТОР</button>
                    </td>

		        </tr>
		    </table>
		</form>
	</div>
{% endblock %}

home/templates/employee.html
{% extends "base_index.html" %}

{% block title %}<title>LanchBox</title>{% endblock %}
{% block style%}
	<script src="https://code.jquery.com/jquery-3.5.0.js"></script>
    {% load static %}
    <link href="{% static 'css/style.css' %}" rel="stylesheet" >
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
	{% endblock %}
{% block body %}
	<header>
		<div class="search">
			<form action="." method="post">
				{% csrf_token %}
  				<input type="number" name="id_search" id="id_id_search" autofocus placeholder="Искать по номеру заказа...">
  				<button type="submit"></button>
			</form>
			<div class="status">
            <form action="." method="post">
                {% csrf_token %}
				<h3>Режим заполненного зала</h3>
                {% if st == 0 %}
				<input type="hidden" name="id_status" value="1">
				<button type="submit">
					<p>ВКЛЮЧИТЬ</p>
				</button>
                {% else %}
				<input type="hidden" name="id_status" value="0">
				<button type="submit">
					<p style="color: yellow;">ВЫКЛЮЧИТЬ</p>
				</button>
                {% endif %}
            </form>
        </div>

		</div>

		<div class="logotip">
			<h1>LunchBox</h1>
		</div>

		<div class="employee">
			<p>Сотрудник:</p>
			<p>{{userP.username}}</p>
			<a href="{% url 'logoutProfile'%}"><button>ВЫЙТИ</button></a>
		</div>
	</header>

	<main>
		<div class="prepare" id="prepare">
			<!--блок заказов во временном промежутке -->
			<script type="text/javascript">
					function refresh() {
						$('#period').html('').load(
						"{% url 'prepare' %}");
						return false;
					}

					$(function () {
						setInterval('refresh()', 10000);
						return false;
					});
			</script>
			{% include 'prepare.html' %}
		</div>
	</main>

	<footer>
	</footer>
{% endblock %}

home/templates/index.html
{% extends "base_index.html" %}

{% block title %}<title>LanchBox</title>{% endblock %}
{% block style%}
    {% load static %}
    <link href="{% static 'css/style_in.css' %}" rel="stylesheet" >
{% endblock %}
{% block body %}
    <div class="entry">
        {% load static %}
		<img src=" {% static "img\vxod.png" %}" alt="">
		<h1>Вход</h1>
		<form method="post">

		    <table>
                {% csrf_token %}
		        <tr>
		            <td><input type="text" name="username" maxlength="150" autofocus required id="id_username"></td>
		        </tr>
		        <tr>
		            <td><input type="password" name="password1" required id="id_password1"></td>
		        </tr>
		        <tr>
		            <td><input type="submit" value="ВОЙТИ"></td>
		        </tr>
		    </table>
		</form>
	</div>
{% endblock %}

home/templates/order.html
{% extends "base_index.html" %}

{% block title %}<title>LanchBox</title>{% endblock %}
{% block style%}
    {% load static %}
    <link href="{% static 'css/order.css' %}" rel="stylesheet" >
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
{% endblock %}
{% block body %}
    <main>
        <div class="order">
            <h3>Заказ {{order.id}}</h3>
            {% for com in order.order_compositions.all %}
            <p>{{com.lunchbox.title}} - {{com.number}} шт.</p>
            {% endfor %}
            <p>Цена: {{order.price}} руб.</p>
            <form class="readyForm" action="." method="post">
                {% csrf_token %}
                <input type="hidden" name="id_ready" id="id_id_ready" value="{{order.id}}">
                <button class="ready-bn" type="submit">ГОТОВО</button>
            </form>
            <div class="readyForm back">
                <a href="{% url 'employee'%}"><button class="ready-bn">НАЗАД</button></a>
            </div>
        </div>
    </main>

{% endblock %}

home/templates/prepare.html
<div class="period" id="period">
				{% for order in orders %}
                    <div class="orderForm">
                        <form action="." method="post">
                        {% csrf_token %}
                            <button class="order-bn" type="submit">
                                <h3>ЗАКАЗ {{order.id}}</h3>
                                <input type="hidden" name="id_ready" id="id_id_ready" value="{{order.id}}">
                            </button>
                        </form>
                    </div>
				{% endfor %}
</div>

home/templates/redaction_lunch.html
{% block title %}<title>LanchBox</title>{% endblock %}
{% block style%}
    {% load static %}
    <link href="{% static 'css/style_lunch.css' %}" rel="stylesheet" >
{% endblock %}
{% block body %}
    <div class="entry">
        {% load static %}
		<h1>Редактирование ланчбокса</h1>
		<form method="post" action="." enctype="multipart/form-data">
			{% csrf_token %}
		    <table>
		        <tr>
		            <td><p>НАЗВАНИЕ</p><input type="text" name="title" autofocus id="id_title" value="{{lb.title}}" required></td>
		        </tr>
		        <tr>
		            <td><p>ФОТО</p><input type="file" name="lb_img" accept="image/*" value="{{MEDIA_URL}}{{ lb.img.url}}" required id="id_img"></td>
		        </tr>
				<tr>
					<td><p>ОПИСАНИЕ</p><textarea rows="3" type="text" name="description" id="id_description" required>{{lb.description}}</textarea></td>
		        </tr>
		        <tr>
		            <td><p>ЦЕНА</p><input type="number" name="price" id="id_price" value="{{lb.price}}" required></td>
		        </tr>
				<tr>
		            <td><p>ТИП</p><input type="text" name="addition" id="id_addition" value="{{lb.addition}}" required></td>
		        </tr>
		        <tr>
		            <td><input type="submit" value="Редактировать"></td>
		        </tr>
		    </table>
		</form>
	</div>
{% endblock %}

home/templates/statistics.html
{% extends "base_index.html" %}

{% block title %}<title>LanchBox</title>{% endblock %}
{% block style%}
    <script src="https://code.jquery.com/jquery-3.5.0.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>
    {% load static %}
    <link href="{% static 'css/statistics.css' %}" rel="stylesheet" >
{% endblock %}
{% block body %}
    <header>
		<div class="logotip">
			<h1>LunchBox</h1>
		</div>

		<div class="employee">
			<p>Администратор:</p>
			<p>{{userP.username}}</p>
			<a class="stat" href="{% url 'administrator'%}"><button>ГЛАВНАЯ</button></a>
            <a href="{% url 'logoutProfile'%}"><button>ВЫЙТИ</button></a>
		</div>
	</header>
	<main>
        <div class="menu">
            <div id="sales">
                <p>ПРОДАЖИ</p>
            </div>
            <div id="lunchboxs">
                <p>ЛАНЧБОКСЫ</p>
            </div>
            <div id="employees">
                <p>СОТРУДНИКИ</p>
            </div>
        </div>
        <div class="content" id="content">
            {% include 'statistics_sales.html' %}
        </div>

    </main>
    <script>
        $( "#employees" ).click(function() {
            $('#content').html('').load( "{% url 'statistics_employee' %}");
            $('#employees').css('color', 'yellow');
            $('#sales').css('color', 'white');
            $('#lunchboxs').css('color', 'white');
        });
        $( "#sales" ).click(function() {
            $('#content').html('').load( "{% url 'statistics_sales' %}");
            $('#sales').css('color', 'yellow');
            $('#lunchboxs').css('color', 'white');
            $('#employees').css('color', 'white');
        });
        $( "#lunchboxs" ).click(function() {
            $('#content').html('').load( "{% url 'statistics_lunchboxs' %}");
            $('#lunchboxs').css('color', 'yellow');
            $('#sales').css('color', 'white');
            $('#employees').css('color', 'white');
        });
    </script>
{% endblock %}